apiVersion: v1
kind: Service
metadata:
  name: api-estudiantes-service
  labels:
    app: api-estudiantes
spec:
  type: LoadBalancer
  selector:
    app: api-estudiantes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
