// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servicios_Estudiantes.Infraestructura.AccesoDatos;

#nullable disable

namespace Servicios_Estudiantes.Infraestructura.Migrations
{
    [DbContext(typeof(EstudiantesDbContext))]
    partial class EstudiantesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AulaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("AulaId");

                    b.ToTable("Aula", (string)null);

                    b.HasData(
                        new
                        {
                            AulaId = 1,
                            Capacidad = 30,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "A-101",
                            SedeId = 1
                        },
                        new
                        {
                            AulaId = 2,
                            Capacidad = 40,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "A-102",
                            SedeId = 1
                        },
                        new
                        {
                            AulaId = 3,
                            Capacidad = 25,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "B-201",
                            SedeId = 2
                        });
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramaCreditoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiante", (string)null);
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.InscripcionEstudianteMateria", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("EstudianteId", "MateriaId");

                    b.ToTable("InscripcionEstudianteMateria", (string)null);
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<int?>("AulaId")
                        .HasColumnType("int");

                    b.Property<byte>("Creditos")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramaCreditoId")
                        .HasColumnType("int");

                    b.HasKey("MateriaId");

                    b.ToTable("Materia", (string)null);

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            AulaId = 1,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Nombre = "Álgebra Lineal",
                            ProfesorId = 1,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 2,
                            AulaId = 2,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            Nombre = "Cálculo I",
                            ProfesorId = 1,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 3,
                            AulaId = 1,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            Nombre = "Programación I",
                            ProfesorId = 2,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 4,
                            AulaId = 3,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Nombre = "Estructuras de Datos",
                            ProfesorId = 2,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 5,
                            AulaId = 2,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            Nombre = "Bases de Datos",
                            ProfesorId = 3,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 6,
                            AulaId = 3,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            Nombre = "Sistemas Operativos",
                            ProfesorId = 3,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 7,
                            AulaId = 1,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(16, 0, 0),
                            Nombre = "Redes",
                            ProfesorId = 4,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 8,
                            AulaId = 2,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(18, 0, 0),
                            Nombre = "Seguridad Informática",
                            ProfesorId = 4,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 9,
                            AulaId = 3,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(16, 0, 0),
                            Nombre = "Ingeniería de Software",
                            ProfesorId = 5,
                            ProgramaCreditoId = 1
                        },
                        new
                        {
                            MateriaId = 10,
                            AulaId = 1,
                            Creditos = (byte)3,
                            Estado = (byte)1,
                            FechaFin = new DateOnly(2026, 12, 15),
                            FechaInicio = new DateOnly(2026, 8, 1),
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Nombre = "Gestión de Proyectos",
                            ProfesorId = 5,
                            ProgramaCreditoId = 1
                        });
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesor", (string)null);

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Prof. Ana García"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Prof. Luis Martínez"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Prof. Carmen Ruiz"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Prof. Jorge Soto"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Prof. Elena Vargas"
                        });
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.ProgramaCredito", b =>
                {
                    b.Property<int>("ProgramaCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramaCreditoId"));

                    b.Property<byte>("CreditosPorMateria")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<byte>("MaxMateriasPorEstudiante")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramaCreditoId");

                    b.ToTable("ProgramaCredito", (string)null);

                    b.HasData(
                        new
                        {
                            ProgramaCreditoId = 1,
                            CreditosPorMateria = (byte)3,
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            MaxMateriasPorEstudiante = (byte)3,
                            Nombre = "Ingeniería de software"
                        });
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SedeId");

                    b.ToTable("Sede", (string)null);

                    b.HasData(
                        new
                        {
                            SedeId = 1,
                            Direccion = "Calle 123",
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Sede Principal"
                        },
                        new
                        {
                            SedeId = 2,
                            Direccion = "Avenida 45",
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            Nombre = "Sede Norte"
                        });
                });

            modelBuilder.Entity("Servicios_Estudiantes.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Email = "admin@local.test",
                            Estado = (byte)1,
                            FechaRegistro = new DateTime(2026, 8, 21, 0, 9, 54, 564, DateTimeKind.Utc).AddTicks(126),
                            NombreUsuario = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUYADfSZ2TyLmEJjXSQVXyehyd/8I0XdpR0kBnq65pRMiA1G9a+PKzL1uvr6fbcyA==",
                            Rol = "Administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
